---
title: "Plotting genomic functional annotation for Haddock Epigenetic Aging Project"
author: "Authors: Emma Strand; emma.strand@gmgi.org"
output:
  github_document: default
  pdf_document:
    keep_tex: yes
  html_document:
    toc: yes
    toc_depth: 6
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---

Load libraries

```{r}
library(tidyverse)
library(ggplot2)
library(readxl) ## read excel file 
library(writexl) ## write excel file 
library(ggpubr)
library(ComplexHeatmap)
library(matrixStats) # for row normalization
library(circlize)
library(pheatmap)
library(gplots)
library(RColorBrewer)
```

Load data 

```{r}
functional_clock <- read.csv("data/06_genomic_function/functional_clock.csv") %>% dplyr::select(-X)
length(unique(functional_clock$Loc)) ##81

# folder is zipped 
# functional_100p <- read.csv("data/06_genomic_function/functional_100p.csv") %>% dplyr::select(-X)
# length(unique(functional_100p$Loc))

functional_90p <- read.csv("data/06_genomic_function/functional_90p.csv") %>% dplyr::select(-X)
length(unique(functional_90p$Loc)) # 33,703
```

```{r}
# 1. Read data
clock_data <- read.csv("data/04_age_prediction/clock_data.csv") %>% dplyr::select(-X)
full100_data <- read.csv("data/04_age_prediction/full100p_data.csv") %>% dplyr::select(-X)
full90_data <- read.csv("data/04_age_prediction/full90p_data.csv") %>% dplyr::select(-X)

# 2. Prepare clock_matrix (rows: Loc, columns: GMGI_ID)
clock_matrix <- clock_data %>% 
  spread(GMGI_ID, percent.meth) %>%
  column_to_rownames(var = "Loc")
clock_matrix <- as.matrix(clock_matrix)
clock_matrix <- clock_matrix[, sample_order]

# 3a. Prepare full100_matrix  
full100_matrix <- full100_data %>%
  dplyr::select(Loc, sample, percent.meth) %>%
  spread(sample, percent.meth) %>%
  column_to_rownames(var = "Loc")
full100_matrix <- as.matrix(full100_matrix)

# 3b. Prepare full90_matrix  
full90_matrix <- full90_data %>%
  dplyr::select(Loc, sampleID, percent.meth) %>%
  spread(sampleID, percent.meth) %>%
  column_to_rownames(var = "Loc")
full90_matrix <- as.matrix(full90_matrix)

# 4. Read in prediction data for the Ages of individuals used
best_clock <- read.csv("data/04_age_prediction/predictions.csv") %>% dplyr::select(GMGI_ID, AgeRounded) %>% arrange(AgeRounded)
sample_order <- best_clock$GMGI_ID
age_order <- best_clock$AgeRounded

# 5. Order the matrices by the Age
clock_matrix <- clock_matrix[, sample_order]
full100_matrix <- full100_matrix[, sample_order]
full90_matrix <- full90_matrix[, sample_order]
```

Heatmap for clock loci

```{r}
# Z-score by row (locus-wise)
clock_matrix_z <- t(scale(t(clock_matrix)))
clock_matrix_z <- clock_matrix_z[, sample_order]

# Now plot the heatmap using your parameters
age_annot <- best_clock$AgeRounded[match(colnames(clock_matrix_z), best_clock$GMGI_ID)]

# 2. Create top annotation
hm_ann_col <- HeatmapAnnotation(
  Age = age_annot,
  col = list(Age = colorRamp2(range(age_annot, na.rm = TRUE), c("#d8f3dc", "#3a5a40"))),
  annotation_name_side = "left"
)

z_col_fun <- colorRamp2(c(-2, 0, 2), c("white", "white", "#013a63"))

pdf("manuscript figures/Figure4_heatmapv2.pdf")
ht <- 
  Heatmap(
  clock_matrix_z,
  column_title = "",
  name = "z-score",
  show_row_names = FALSE,
  top_annotation = hm_ann_col,
  show_column_names = FALSE,
  cluster_columns = FALSE,
  row_dend_side = "left",
  column_dend_height = unit(0.5, "in"),
  km = 2,
  col = z_col_fun,
  row_km_repeats = 100,
  row_gap = unit(2.5, "mm"),
  row_title = c("Cluster1", "Cluster2"),
  border = TRUE,
  column_names_gp = gpar(fontsize = 8),
  # Adjust these to control cell size:
  width = unit(8, "cm"),   # Narrower width = smaller column boxes
  height = unit(8, "cm")  # Shorter height = smaller row boxes
)
ht_drawn <- draw(ht)
dev.off()
```

Heatmap for 100% loci

```{r}
# Z-score by row (locus-wise)
full100_matrix_z <- t(scale(t(full100_matrix)))
full100_matrix_z <- full100_matrix_z[, sample_order]

# Now plot the heatmap using your parameters
age_annot_full <- best_clock$AgeRounded[match(colnames(full100_matrix_z), best_clock$GMGI_ID)]

# 2. Create top annotation
hm_ann_col_full <- HeatmapAnnotation(
  Age = age_annot_full,
  col = list(Age = colorRamp2(range(age_annot, na.rm = TRUE), c("#d8f3dc", "#3a5a40"))),
  annotation_name_side = "left"
)

z_col_fun <- colorRamp2(c(-2, 0, 2), c("white", "white", "#013a63"))

pdf("manuscript figures/Figure4_heatmap_100p_v2.pdf")
ht_full <- 
  Heatmap(
  full100_matrix_z,
  column_title = "",
  name = "z-score",
  show_row_names = FALSE,
  top_annotation = hm_ann_col,
  show_column_names = FALSE,
  cluster_columns = FALSE,
  row_dend_side = "left",
  row_dend_width = unit(2, "mm"),
  column_dend_height = unit(0.5, "in"),
  km = 2,
  col = z_col_fun,
  row_km_repeats = 100,
  row_gap = unit(2.5, "mm"),
  row_title = c("Cluster1", "Cluster2"),
  border = TRUE,
  column_names_gp = gpar(fontsize = 8),
  # Adjust these to control cell size:
  width = unit(8, "cm"),   # Narrower width = smaller column boxes
  height = unit(8, "cm")  # Shorter height = smaller row boxes
)
ht_full_drawn <- draw(ht_full)
dev.off()
```

Heatmap for 90% loci

```{r}
# Z-score by row (locus-wise)
full90_matrix_z <- t(scale(t(full90_matrix)))
full90_matrix_z <- full90_matrix_z[, sample_order]

# Now plot the heatmap using your parameters
age_annot_full <- best_clock$AgeRounded[match(colnames(full90_matrix_z), best_clock$GMGI_ID)]

# 2. Create top annotation
hm_ann_col_full <- HeatmapAnnotation(
  Age = age_annot_full,
  col = list(Age = colorRamp2(range(age_annot_full, na.rm = TRUE), c("#d8f3dc", "#3a5a40"))),
  annotation_name_side = "left"
)

z_col_fun <- colorRamp2(c(-2, 0, 2), c("white", "white", "#013a63"))

pdf("manuscript figures/Figure4_heatmap_90p_v2.pdf")
ht_full <- 
  Heatmap(
  full90_matrix_z,
  column_title = "",
  name = "z-score",
  show_row_names = FALSE,
  top_annotation = hm_ann_col_full,
  show_column_names = FALSE,
  cluster_columns = FALSE,
  row_dend_side = "left",
  row_dend_width = unit(2, "mm"),
  column_dend_height = unit(0.5, "in"),
  km = 2,
  col = z_col_fun,
  row_km_repeats = 100,
  row_gap = unit(2.5, "mm"),
  row_title = c("Cluster1", "Cluster2"),
  border = TRUE,
  column_names_gp = gpar(fontsize = 8),
  # Adjust these to control cell size:
  width = unit(12, "cm"),   # Narrower width = smaller column boxes
  height = unit(12, "cm")  # Shorter height = smaller row boxes
)
ht_full_drawn <- draw(ht_full)
dev.off()
```





Cluster Loci to then map function 

```{r}
# Get the row indices for each cluster
cluster1_rows <- row_order(ht_drawn)[[1]]
cluster2_rows <- row_order(ht_drawn)[[2]]

# Get the row names (assuming rownames(clock_matrix_z) are your feature names)
cluster1_names <- as.data.frame(rownames(clock_matrix_z)[cluster1_rows]) %>% rename(Loc=1) %>% mutate(cluster="1") ## 66 loci
cluster2_names <- as.data.frame(rownames(clock_matrix_z)[cluster2_rows]) %>% rename(Loc=1) %>% mutate(cluster="2") ## 45 loci

names_total <- bind_rows(cluster1_names, cluster2_names)

## Cluster df 
cluster_information <- functional_clock %>% full_join(., names_total, by = "Loc")

cluster_information %>% group_by(cluster, Note) %>% summarise(count = n_distinct(Loc)) %>% write_xlsx("data/functional_notes.xlsx")

### Export gene list 
cluster_information %>% dplyr::select(Name, cluster) %>%
  mutate(Name = gsub("Name=", "", Name)) %>% write.csv("data/cluster_genelist.csv", row.names = FALSE)
```


Cluster Loci to then map function for 100% set

```{r}
which_matrix <- full90_matrix_z

# Get the row indices for each cluster
cluster1_full_rows <- row_order(ht_full_drawn)[[1]]
cluster2_full_rows <- row_order(ht_full_drawn)[[2]]

# Get the row names (assuming rownames(clock_matrix_z) are your feature names)
cluster1_full_names <- as.data.frame(rownames(which_matrix)[cluster1_full_rows]) %>% 
  rename(Loc=1) %>% mutate(cluster="1") ## 3,554 loci for 100% ; 28,762 loci for 90%

cluster2_full_names <- as.data.frame(rownames(which_matrix)[cluster2_full_rows]) %>% 
  rename(Loc=1) %>% mutate(cluster="2") ## 4,177 loci; 18,611 loci for 90%

names_full_total <- bind_rows(cluster1_full_names, cluster2_full_names)

## Cluster df 
cluster_full_information <- functional_90p %>% 
  mutate(Loc=gsub("\\|", "_", Loc),
         Loc=gsub(" ", "_", Loc)) %>%
  full_join(., names_full_total, by = "Loc")

cluster_full_information %>% group_by(cluster) %>% summarise(count = n_distinct(Name))# %>% #write_xlsx("data/functional_notes.xlsx")

### Export gene list 
cluster_full_information %>% dplyr::select(Name, cluster) %>%
  #mutate(Name = gsub("Name=", "", Name)) %>% 
  write.csv("data/06_genomic_function/cluster_90p_genelist.csv", row.names = FALSE)
```

















