---
title: "Plotting genomic location for Haddock Epigenetic Aging Project"
author: "Authors: Emma Strand; emma.strand@gmgi.org"
output:
  github_document: default
  pdf_document:
    keep_tex: yes
  html_document:
    toc: yes
    toc_depth: 6
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---

Load libraries

```{r}
library(tidyverse)
library(ggplot2)
library(readxl) ## read excel file 
library(writexl) ## write excel file 
library(ggpubr)
```

Load data 

```{r}
location90p <- read.csv("data/05_genomic_location/90p_genomiclocation-8-7-2026.csv")
location100p <- read.csv("data/05_genomic_location/100p_genomiclocation-8-7-2026.csv")
clock_location <- read.csv("data/05_genomic_location/clock_genomiclocation-8-7-2026.csv")

scaffold_full <- read.csv("data/05_genomic_location/scaffold_loci_length_100p-8-7-2026.csv")
#scaffold_clock <- read.csv("data/05_genomic_location/scaff")
scaffold_90p <- read.csv("data/05_genomic_location/scaffold_loci_length_90p-8-7-2026.csv")

desired_order <- c("Promoter", "Terminator", "Other", "Intron", "CDS", "UTR5", "UTR3")
```

Plot

```{r}
location100p %>% 
  group_by(feature_type) %>%
  reframe(count = n_distinct(Loc)) %>%
  mutate(feature_type = factor(feature_type, levels = desired_order)) %>%
  
  mutate(x="x") %>%
  
  ggplot(., aes(x=x, y=count)) + 
  
  geom_bar(stat = "identity", position = "stack", aes(fill=feature_type), color='grey20') +
  labs(
    y="Number of CpG Loci",
    x="",
    fill=""
  ) +
  scale_fill_manual(values = c("#F3FBEF", "#C2E1C4", "#9CC398", "#caf0f8", "#8ecae6", "#61a5c2", "#0077b6")) +
  theme_bw() +
  scale_y_continuous(labels = scales::comma) +
  theme(
    axis.text.x = element_blank(),
    legend.position = "right",
    axis.text.y = element_text(size=10, color="black"),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size=12, face="bold")
  )

ggsave("manuscript figures/Figure3_genomic100p.png", width=4, height=5)
```


```{r}
clock_location %>% 
  
  group_by(feature_type) %>%
  reframe(count = n_distinct(Loc)) %>%
  mutate(feature_type = factor(feature_type, levels = desired_order)) %>%
  
  mutate(x="x") %>%
  
  ggplot(., aes(x=x, y=count)) + 
  
  geom_bar(stat = "identity", position = "stack", aes(fill=feature_type), color='grey20') +
  labs(
    y="Number of CpG Loci",
    x="",
    fill=""
  ) +
  scale_y_continuous(labels = scales::comma) +
  scale_fill_manual(values = c("#F3FBEF", "#C2E1C4", "#9CC398", "#8ecae6", "#61a5c2", "#0077b6")) +
  theme_bw() +
  theme(
    axis.text.x = element_blank(),
    legend.position = "right",
    axis.text.y = element_text(size=10, color="black"),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size=12, face="bold")
  )

ggsave("manuscript figures/Figure3_genomic_clock.png", width=3.75, height=5)
```


```{r}
location90p %>% 
  
  group_by(feature_type) %>%
  reframe(count = n_distinct(Loc)) %>%
  mutate(feature_type = factor(feature_type, levels = desired_order)) %>%
  
  mutate(x="x") %>%
  
  ggplot(., aes(x=x, y=count)) + 
  
  geom_bar(stat = "identity", position = "stack", aes(fill=feature_type), color='grey20') +
  labs(
    y="Number of CpG Loci",
    x="",
    fill=""
  ) +
  scale_y_continuous(labels = scales::comma) +
  scale_fill_manual(values = c("#F3FBEF", "#C2E1C4", "#9CC398", "#caf0f8", "#8ecae6", "#61a5c2", "#0077b6")) +
  theme_bw() +
  theme(
    axis.text.x = element_blank(),
    legend.position = "right",
    axis.text.y = element_text(size=10, color="black"),
    axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0), size=12, face="bold")
  )

ggsave("manuscript figures/Figure3_genomic_90p.png", width=4, height=5)
```


Scaffold plot

```{r}
scaffold_90p %>%
  mutate(Sequence.Length = as.numeric(Sequence.Length),
         Log.Length = log10(Sequence.Length),
         Ratio = number_of_loci/Sequence.Length
         ) %>%
  
  ggplot(aes(x = Sequence.Length, y = number_of_loci)) + 
  geom_point(size = 1.5, shape = 21, fill = "grey80", color = "black", alpha = 0.5) +
  labs(
    y = "Number of age-associated CpG loci",
    x = "Scaffold length (bp)"
  ) +
  scale_x_continuous(expand = expansion(mult = c(0.025, 0.05)),
                     labels = scales::label_comma()) +
  theme_bw() +
  theme(
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size = 10, color = "black"),
    axis.text.x = element_text(size = 10, color = "black"),
    axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 0), size = 13),
    axis.title.x = element_text(margin = margin(t = 15, r = 0, b = 0, l = 0), size = 13)
  )

ggsave("manuscript figures/Figure3_scaffolds.png", width=6, height=4)
```


```{r}
clock_location %>% separate(Loc, into = c("Scaffold", "Position"), remove=F) %>% dplyr::select(Scaffold) %>%
  distinct()
## 100 scaffolds
```

### Statistics 

```{r}
clock_location %>% group_by(feature_type) %>%
  reframe(count = n_distinct(Loc))

clock_genic <- 33+48+2+3
clock_nongenic <- 22+1

location90p  %>% group_by(feature_type) %>%
  reframe(count = n_distinct(Loc))

background_genic <- 15595+31848+1212+1307
background_nongenic <- 843+802+16234
```


```{r}
tab <- matrix(
  c(clock_genic,
    clock_nongenic,
    background_genic - clock_genic,
    background_nongenic - clock_nongenic),
  nrow = 2,
  byrow = TRUE
)

rownames(tab) <- c("Clock", "Background")
colnames(tab) <- c("Genic", "Non-genic")

tab

chisq.test(tab)
```








